---
name: CI
'on':
  pull_request:
  push:
    branches:
      - master
# It will run the action when pull_request and push to the master branch.

jobs:

  test:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - centos8
          - debian10
    
    steps:
      - name: Checkout the codebase.
        uses: actions/checkout@v2
      
      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install test dependencies.
        run: pip3 install molecule docker yamllint ansible-lint
        
      - name: Run Molecule Tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
        
Now add the files, commit and push the changes.